// Controller Remote Access Protocol (CRAP) sketch for Arduino Uno rev. 3

/** Send one byte. */
void send1(byte value) {
  Serial.write(value);
  Serial.flush();
}

/** Send two bytes. */
void send2(int value) {
  Serial.write(value & 255);
  Serial.write(value >> 8 & 255);
  Serial.flush();
}

/** Send four bytes. */
void send4(long value) {
  Serial.write(value & 255);
  Serial.write(value >> 8 & 255);
  Serial.write(value >> 16 & 255);
  Serial.write(value >> 24 & 255);
  Serial.flush();
}

void (*procedure[])() = {
  [] { send4(millis()); },
  [] { noInterrupts(); },
  [] { interrupts(); },
  [] { analogReference(DEFAULT); },
  [] { analogReference(EXTERNAL); },
  [] { analogReference(INTERNAL); },
  [] { send1(digitalRead(2)); },
  [] { digitalWrite(2, HIGH); },
  [] { digitalWrite(2, LOW); },
  [] { pinMode(2, INPUT); },
  [] { pinMode(2, INPUT_PULLUP); },
  [] { pinMode(2, OUTPUT); },
  [] { send1(digitalRead(3)); },
  [] { digitalWrite(3, HIGH); },
  [] { digitalWrite(3, LOW); },
  [] { pinMode(3, INPUT); },
  [] { pinMode(3, INPUT_PULLUP); },
  [] { pinMode(3, OUTPUT); },
  [] { send1(digitalRead(4)); },
  [] { digitalWrite(4, HIGH); },
  [] { digitalWrite(4, LOW); },
  [] { pinMode(4, INPUT); },
  [] { pinMode(4, INPUT_PULLUP); },
  [] { pinMode(4, OUTPUT); },
  [] { send1(digitalRead(5)); },
  [] { digitalWrite(5, HIGH); },
  [] { digitalWrite(5, LOW); },
  [] { pinMode(5, INPUT); },
  [] { pinMode(5, INPUT_PULLUP); },
  [] { pinMode(5, OUTPUT); },
  [] { send1(digitalRead(6)); },
  [] { digitalWrite(6, HIGH); },
  [] { digitalWrite(6, LOW); },
  [] { pinMode(6, INPUT); },
  [] { pinMode(6, INPUT_PULLUP); },
  [] { pinMode(6, OUTPUT); },
  [] { send1(digitalRead(7)); },
  [] { digitalWrite(7, HIGH); },
  [] { digitalWrite(7, LOW); },
  [] { pinMode(7, INPUT); },
  [] { pinMode(7, INPUT_PULLUP); },
  [] { pinMode(7, OUTPUT); },
  [] { send1(digitalRead(8)); },
  [] { digitalWrite(8, HIGH); },
  [] { digitalWrite(8, LOW); },
  [] { pinMode(8, INPUT); },
  [] { pinMode(8, INPUT_PULLUP); },
  [] { pinMode(8, OUTPUT); },
  [] { send1(digitalRead(9)); },
  [] { digitalWrite(9, HIGH); },
  [] { digitalWrite(9, LOW); },
  [] { pinMode(9, INPUT); },
  [] { pinMode(9, INPUT_PULLUP); },
  [] { pinMode(9, OUTPUT); },
  [] { send1(digitalRead(10)); },
  [] { digitalWrite(10, HIGH); },
  [] { digitalWrite(10, LOW); },
  [] { pinMode(10, INPUT); },
  [] { pinMode(10, INPUT_PULLUP); },
  [] { pinMode(10, OUTPUT); },
  [] { send1(digitalRead(11)); },
  [] { digitalWrite(11, HIGH); },
  [] { digitalWrite(11, LOW); },
  [] { pinMode(11, INPUT); },
  [] { pinMode(11, INPUT_PULLUP); },
  [] { pinMode(11, OUTPUT); },
  [] { send1(digitalRead(12)); },
  [] { digitalWrite(12, HIGH); },
  [] { digitalWrite(12, LOW); },
  [] { pinMode(12, INPUT); },
  [] { pinMode(12, INPUT_PULLUP); },
  [] { pinMode(12, OUTPUT); },
  [] { send1(digitalRead(13)); },
  [] { digitalWrite(13, HIGH); },
  [] { digitalWrite(13, LOW); },
  [] { pinMode(13, INPUT); },
  [] { pinMode(13, INPUT_PULLUP); },
  [] { pinMode(13, OUTPUT); },
  [] { send1(digitalRead(A0)); },
  [] { digitalWrite(A0, HIGH); },
  [] { digitalWrite(A0, LOW); },
  [] { pinMode(A0, INPUT); },
  [] { pinMode(A0, INPUT_PULLUP); },
  [] { pinMode(A0, OUTPUT); },
  [] { send2(analogRead(A0)); },
  [] { send1(digitalRead(A1)); },
  [] { digitalWrite(A1, HIGH); },
  [] { digitalWrite(A1, LOW); },
  [] { pinMode(A1, INPUT); },
  [] { pinMode(A1, INPUT_PULLUP); },
  [] { pinMode(A1, OUTPUT); },
  [] { send2(analogRead(A1)); },
  [] { send1(digitalRead(A2)); },
  [] { digitalWrite(A2, HIGH); },
  [] { digitalWrite(A2, LOW); },
  [] { pinMode(A2, INPUT); },
  [] { pinMode(A2, INPUT_PULLUP); },
  [] { pinMode(A2, OUTPUT); },
  [] { send2(analogRead(A2)); },
  [] { send1(digitalRead(A3)); },
  [] { digitalWrite(A3, HIGH); },
  [] { digitalWrite(A3, LOW); },
  [] { pinMode(A3, INPUT); },
  [] { pinMode(A3, INPUT_PULLUP); },
  [] { pinMode(A3, OUTPUT); },
  [] { send2(analogRead(A3)); },
  [] { send1(digitalRead(A4)); },
  [] { digitalWrite(A4, HIGH); },
  [] { digitalWrite(A4, LOW); },
  [] { pinMode(A4, INPUT); },
  [] { pinMode(A4, INPUT_PULLUP); },
  [] { pinMode(A4, OUTPUT); },
  [] { send2(analogRead(A4)); },
  [] { send1(digitalRead(A5)); },
  [] { digitalWrite(A5, HIGH); },
  [] { digitalWrite(A5, LOW); },
  [] { pinMode(A5, INPUT); },
  [] { pinMode(A5, INPUT_PULLUP); },
  [] { pinMode(A5, OUTPUT); },
  [] { send2(analogRead(A5)); },
};
